---
title: 异步
date: 2021-08-30 17:04:01
permalink: /pages/39ce64/
categories:
  - 前端
  - 三剑客
  - Javscript
tags:
  -
---

## 单线程和异步

- JS 是单线程语言，只能同时做一件事
- 浏览器和 nodejs 已经支持 JS 启动进程，如 web worker
- JS 和 DOM 渲染共用一个线程，因为 JS 可修改 DOM 结构

  - 为什么我们要使用异步呢？  
    因为 JS 是单线程，只能同时做一件事情。当遇到等待（网络请求，定时任务）不能卡住的时候，需要用异步来解决。  
    划重点`异步是为了解决单线程等待的问题`

  - 异步是怎么实现的？  
    异步是基于 callback 函数形式来调用

**最基础的异步是 setTimeout 和 setInterval 函数。**

```js
//  异步
console.log(100)
setTimeout(() => {
  console.log(200)
}, 1000)
console.log(300)
// 100 300 200
```

> 先打印 100，然后停 1 秒钟，在停顿的时候，先打印 300 之后，再去打印 100。

```js
// 同步
console.log(100)
alert(200)
console.log(300)
```

> 先打印 100 ，然后执行 alert200, 最后在打印 300，按照顺序执行。

### 异步和同步

- 基于 JS 是单线程语言
- 异步不会堵塞代码执行
- 同步会堵塞代码执行

### 异步的应用场景

- ajax
  ```js
  console.log('start')
  $.get('./data1.json', function(data1) {
    console.log(data1)
  })
  console.log('end')
  ```

## event loop(事件循环/事件轮询)

JS 是单线程运行的，异步要基于回调来实现，event loop 就是异步回调的原理。

### js 如何执行？

- 从前到后，一行行执行
- 如果某一行执行报错，则停止下面代码的执行
- 先把同步代码执行，在执行异步

### event loop 的执行过程

1. 从前往后，一行行执行代码
2. 遇到异步，会先记录下，等待时机（定时，网络请求等）
3. 时机到了，放到 callback Queue

4. 如 call Stack 为空（代码执行完毕）Event loop 开始工作
5. 轮询查找 callback queue,如有则移动到 call stack 执行
6. 然后继续轮询查找

### DOM 事件和 event loop 关系

js 是单线程
异步(setTimeout,ajax 等)使用回调，基于 event loop
DOM 事件也是使用回调，基于 event loop 实现

```js

  <button id="btn1">提交</button>
<script>
console.log('hi')
$('#btn1').click(funtion(e) {
	console.log('button clicked')
})
console.log('Bye')
</script>
```

> `$('#btn1').click(funtion(e)`在 call stack 里面已经执行了，函数里面的内容放到 web APIs 里面.  
> 当用户触发点击事件，就会把它移动 callback queue,event loop 调用移动到 call stack 里面执行

## Promise

### promise 的基本使用

```js
function getData(url) {
  return new Promise((resolve, reject) => {
    $.ajax({
      url,
      success(data) {
        resolve(data)
      },
      error(err) {
        reject(err)
      },
    })
  })
}
const url1 = './data1.json'
const url2 = './data2.json'

getdata(url)
  .then((data1) => {
    console.log(data1)
    return getData(utl2)
  })
  .then((data2) => {
    console.log(data2)
  })
```

- Promise 写法:

  - promise .then 还是 callback 回调函数形式，但是它把 callback 形式变成了非嵌套，管道串联的形式。

- promise 语法:
  - return new Promise
  - new Promise 传入一个函数,函数里面有两个参数
    - resolve
    - reject
  - 当 success 成功的时候，执行 resolve 函数，把 data 返回出去
  - 当失败的时候，执行 error
  - 当触发 succes/error 时，同时也会触发.then/.catch

::: warning
主要理解 Promise 是为了解决什么问题
`主要是为了解决callback hell 回调地狱的问题（callback嵌套）`
:::

### Promise 三种状态，状态的表现和变化

- 三种状态

  - pendding (过程中)
  - resolve (成功)
  - reject (错误)

- 状态变化

  - pedding -> resolveed/pedding -> rejected

- 状态表现

  - pedding 不会触发回调
  - resolved 触发 then 回调
  - rejected 触发 catch 回调

```js
// 想要一个resolve状态的Promise
const p1 = Promise.resolve(100) // resolved

p1.then((data) => {
  console.log('data', data) // 触发.then函数
}).catch((err) => {
  console.log('err', err)
})

// 想要一个reject状态的Promise
const p2 = Promise.reject(100) // rejected

p2.then((data) => {
  console.log('data2', data)
}).catch((err) => {
  console.log('err2', err) // 触发.catch函数
})
```

### Promise then 和 catch 改变状态

- then 正常返回 resolved 状态，里面有报错则返回 rejected 状态
- catch 正常返回 resolved 状态，里面有报错这返回 rejected 状态

  - Promise.resolve()

  ```js
  const p1 = Promise.resolve().then(() => {
    return 100 // 没有报错 状态是 resolved
  })
  // p1 resolved状态  触发后续 .then回调
  p1.then(() => {
    console.log(123)
  })
  // 123

  const p2 = Promise.resolve().then(() => {
    throw new Error('throw error') // 有报错，状态为rejected
  })
  // p2 rejected状态 触发后续 .catch回调
  p2.then(() => {
    console.log('p2: then状态')
  }).catch(() => {
    console.log('p2: catch状态')
  })
  // p2: catch状态
  ```

  - Promise.reject()

  ```js
  const p3 = Promise.reject().catch((err) => {
    console.error(err) // 没有报错 状态是 resolved
  })
  console.log('p3', p3)
  p3.then(() => {
    // p3 resolved状态 触发后续 .then 回调
    console.log('p3: 状态')
  })

  const p4 = Promise.reject().catch((err) => {
    throw new Error('catch error') // 有报错 状态是 rejected
  })
  p4.then(() => {
    console.log('p4: 状态=>resolved')
  }).catch(() => {
    console.log('P4: 状态=>rejected') // p4 rejected状态触发后续 .catch回调
  })
  ```

## naync/await 语法

- 背景

  - nayn-await 是为了解决 异步回调 callback hell
  - 虽然 Promise then catch 链式调用也可以解决这个问题，但是它也是基于回调函数
  - async/awaite 是同步语法，可以消灭回调函数

- 语法介绍  
  用同步的方式，编写异步。

```js
function loadImg(src) {
  const promise = new Promise((resolve, reject) => {
    const img = document.createElement('img')
    img.onload = () => {
      resolve(img)
    }
    img.onerror = () => {
      reject(new Error(`图片加载失败 ${src}`))
    }
    img.src = src
  })
  return promise
}

async function loadImg1() {
  const src1 = 'http://www.imooc.com/static/img/index/logo_new.png'
  const img1 = await loadImg(src1)
  return img1
}

async function loadImg2() {
  const src2 = 'https://avatars3.githubusercontent.com/u/9583120'
  const img2 = await loadImg(src2)
  return img2
}
;(async function() {
  // 注意：await 必须放在 async 函数中，否则会报错
  try {
    // 加载第一张图片
    const img1 = await loadImg1()
    console.log(img1)
    // 加载第二张图片
    const img2 = await loadImg2()
    console.log(img2)
  } catch (ex) {
    console.error(ex)
  }
})()
```

### async/await 和 Promise 的关系

- 执行 async 函数返回结果都是 Promise 对象（如果函数内没返回 Promise ，则自动封装一下）
- await 相当于 Promise 的 then
- try..catch 可捕获异常，代替了 Promise 的 actch

  ```js
  async function fn1() {
    return 100 // 相当于return Promise.resolve(100)
  }

  const p1 = fn1() // 执行async 返回的结果，是一个promise对象
  console.log(p1)
  // Promise {<fulfilled>: 100}

  p1.then((data) => {
    console.log(data)
  })
  // 100

  console.log('======分界线======')

  async function fn2() {
    return Promise.resolve(200) // 返回的本身是一个promise
  }
  const p2 = fn2()
  console.log(p2)
  // Promise {<pending>}

  p2.then((data) => {
    console.log(data)
  })
  // 200
  ```

async 返回结果，是一个 Promise 对象;如果返回的是一个已知的结果，则会自动封装成一个 Promise 对象。

```js
!(async function() {
  const p1 = Promise.resolve(300)
  const data = await p1 // await 相当于Promie then
  console.log('data:', data)
})()
// 300

!(async function() {
  const data2 = await 400 // await 相当于Promie.resolve(400)
  console.log('data2:', data2)
})()

async function fn1() {
  return Promise.resolve(200)
}

!(async function() {
  const data3 = await fn1() // fn1 返回的是一个Promie函数
  console.log('data3:', data3)
})()
// 200
```

await 相当于 Promise 的 then

```js
!(async function() {
  const p1 = Promise.resolve(300)
  const data = await p1 // await 相当于Promie then
  console.log('data:', data)
})()
// 300

!(async function() {
  const data2 = await 400 // await 相当于Promie.resolve(400)
  console.log('data2:', data2)
})()

async function fn1() {
  return Promise.resolve(200)
}

!(async function() {
  const data3 = await fn1() // fn1 返回的是一个Promie函数
  console.log('data3:', data3)
})()
// 200

!(async function() {
  const data4 = Promise.reject('err1') // Promise 状态是rejected
  const res = await data4 // await是相当于then,然后又因为这里的Promise 状态时rejected,所以这里就不会被执行
  console.log('res:', res)
})()
// Uncaught (in promise) err1
```

try...catch 捕获 rejected 状态

```js
;(async function() {
  const p4 = Promise.reject('some err')
  try {
    const res = await p4
    console.log(res)
  } catch (ex) {
    console.error(ex)
  }
})()
```

:::tip 总结

- async 封装 Promise
- await 处理 Promise 成功
- try...catch 处理 Promise 失败
  :::

## 异步的本质

async/awai 是语法糖，异步的本质是回调函数。
async/await 是从语法程度解决异步回调（callback hell）问题的一种解决手段，但本质上它消灭不了单线程 ，异步。异步还是需要基于 event loop 来实现跟执行。

## 微任务和宏任务的区别

- 宏任务 DOM 渲染后触发，setTimeout,setInterval,Ajax,DOM 事件
- 微任务: DOM 渲染前触发，Promise，async/await
- 微任务执行时机比宏任务要,微任务执行时机在 DOM 渲染之前，宏任务在 DOM 渲染之后

## 微任务和宏任务的根本区别

- 宏任务是浏览器规定的
- 微任务是 ES6 语法规定的

总结：宏任务有哪些？微任务有哪些？微任务触发时机更早
微任务，宏任务和 DOM 渲染的关系
微任务，宏任务和 DOM 渲染，在 event loop 的过程

async await 是微任,event loop 是宏任务
